### ISSUE TITLE
Proper way to add jar to classpath? (java.lang.ClassNotFoundException: org.apache.storm.daemon.metrics.MetricsUtils)

### ISSUE THREAD

**Issue by jfr2102** [wizenoze/storm-metrics-reporter-prometheus#3]
Hey, thank you for this project!

I am trying to include the reporter into my storm-cluster running on docker containers.
- The jar from the relase page is included, in storms /extlib/ and /extlib-deamon/ directories.
- storm.yaml configures it as a reporter:
```yaml
- class: "com.wizenoze.storm.metrics2.reporters.PrometheusStormReporter"
    daemons:
        - "supervisor"
        - "nimbus"
        - "worker"
    report.period: 10
    report.period.units: "SECONDS" 
    prometheus.scheme: "http"
    prometheus.host: "pushgateway"
    prometheus.port: 9091
```
 Leads to dead topologies and same error in all worker logs:
```Java
java.lang.Error: java.lang.NoClassDefFoundError: org/apache/storm/daemon/metrics/MetricsUtils
	at org.apache.storm.utils.Utils.handleUncaughtException(Utils.java:655) ~[storm-client-2.2.0.jar:2.2.0]
	at org.apache.storm.utils.Utils.handleUncaughtException(Utils.java:634) ~[storm-client-2.2.0.jar:2.2.0]
	at org.apache.storm.utils.Utils.lambda$createDefaultUncaughtExceptionHandler$2(Utils.java:1016) ~[storm-client-2.2.0.jar:2.2.0]
	at java.lang.ThreadGroup.uncaughtException(Unknown Source) [?:?]
	at java.lang.ThreadGroup.uncaughtException(Unknown Source) [?:?]
	at java.lang.Thread.dispatchUncaughtException(Unknown Source) [?:?]
Caused by: java.lang.NoClassDefFoundError: org/apache/storm/daemon/metrics/MetricsUtils
	at com.wizenoze.storm.metrics2.reporters.PrometheusStormReporter.prepare(PrometheusStormReporter.java:46) ~[storm-metrics-reporter-prometheus-0.0.2.jar:?]
	at org.apache.storm.metrics2.StormMetricRegistry.startReporter(StormMetricRegistry.java:209) ~[storm-client-2.2.0.jar:2.2.0]
	at org.apache.storm.metrics2.StormMetricRegistry.start(StormMetricRegistry.java:197) ~[storm-client-2.2.0.jar:2.2.0]
	at org.apache.storm.daemon.worker.Worker.start(Worker.java:178) ~[storm-client-2.2.0.jar:2.2.0]
	at org.apache.storm.daemon.worker.Worker.main(Worker.java:153) ~[storm-client-2.2.0.jar:2.2.0]
Caused by: java.lang.ClassNotFoundException: org.apache.storm.daemon.metrics.MetricsUtils
	at jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at com.wizenoze.storm.metrics2.reporters.PrometheusStormReporter.prepare(PrometheusStormReporter.java:46) ~[storm-metrics-reporter-prometheus-0.0.2.jar:?]
	at org.apache.storm.metrics2.StormMetricRegistry.startReporter(StormMetricRegistry.java:209) ~[storm-client-2.2.0.jar:2.2.0]
	at org.apache.storm.metrics2.StormMetricRegistry.start(StormMetricRegistry.java:197) ~[storm-client-2.2.0.jar:2.2.0]
	at org.apache.storm.daemon.worker.Worker.start(Worker.java:178) ~[storm-client-2.2.0.jar:2.2.0]
	at org.apache.storm.daemon.worker.Worker.main(Worker.java:153) ~[storm-client-2.2.0.jar:2.2.0]
root@86fdb79c35cb:/logs/workers-artifacts/KafkaTopology-1-1633434022/6700# 
```
Storm version is 2.2.0
Do i have to add anything else to my maven own maven project e.g.?
Thank you for any suggestions!

**Comment by jfr2102** [comment]
Closed:
- No classpath problem, just dependency issue
- using org.apache.storm.daemon.metrics.ClientMetricsUtils instead of org.apache.storm.daemon.metrics.MetricsUtils
-  org.apache.storm.utils.ObjectReader replacing org.apache.storm.utils.Utils
- quick and dirty fix (not working for all metrics, but fine when filtering properly) : [storm-metrics-reporter-prometheus-fork](https://github.com/jfr2102/storm-metrics-reporter-prometheus/releases/tag/0.0.3)
